name: generate github stats

on:
  schedule:
    - cron: "0 0 * * *" # Запуск каждый день в полночь
  workflow_dispatch: # Кнопка ручного запуска
  push:
    branches:
      - main

jobs:
  generate-stats:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # 1. Скачиваем репозиторий (переключаемся на ветку output, если она есть)
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'output'
          # Если ветки output вообще нет, скрипт автоматически создаст её из main
        continue-on-error: true

      # Если ветки output нет, скачиваем main
      - name: Checkout main if output doesn't exist
        if: ${{ failure() || steps.checkout.outcome == 'failure' }}
        uses: actions/checkout@v3
        with:
          ref: 'main'

      # 2. Скачиваем актуальные карточки статистики
      - name: Generate SVGs
        run: |
          # Скачиваем общую статистику
          curl -o github-stats.svg "https://github-readme-stats.vercel.app/api?username=KiloFarsh&show_icons=true&theme=dark&hide_border=true"
          
          # Скачиваем языки (прячем HTML)
          curl -o github-top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=KiloFarsh&layout=compact&theme=dark&hide_border=true&hide=html&exclude_repo=KiloFarsh"
          
          # Меняем "Lua" на "Luau"
          sed -i 's/>Lua</>Luau</g' github-top-langs.svg

      # 3. Пушим файлы напрямую стандартным Git-командой
      - name: Commit and Push to output branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Переключаемся на сиротскую ветку output (чтобы хранить только картинки)
          git checkout --orphan output || git checkout output
          
          # Оставляем только нужные файлы статистики
          git keep github-stats.svg github-top-langs.svg 2>/dev/null || true
          git add github-stats.svg github-top-langs.svg
          
          git commit -m "Update GitHub Statistics" || exit 0
          git push origin output --force
