name: generate github stats

on:
  schedule:
    - cron: "0 0 * * *" # Автоматический запуск каждый день в полночь
  workflow_dispatch: # Позволяет запускать вручную через вкладку Actions
  push:
    branches:
      - main

jobs:
  generate-stats:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # 1. Скачиваем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Создаем папку для картинок
      - name: Create dist directory
        run: mkdir -p dist

      # 3. Скачиваем актуальную карточку общей статистики
      - name: Generate General Stats SVG
        run: |
          curl -o dist/github-stats.svg "https://github-readme-stats.vercel.app/api?username=KiloFarsh&show_icons=true&theme=dark&hide_border=true"

      # 4. Скачиваем актуальную карточку языков (с подменой Lua на Luau и скрытием HTML)
      - name: Generate Top Languages SVG
        run: |
          curl -o dist/github-top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=KiloFarsh&layout=compact&theme=dark&hide_border=true&hide=html&exclude_repo=KiloFarsh"
          # Меняем отображение "Lua" на "Luau" внутри SVG
          sed -i 's/>Lua</>Luau</g' dist/github-top-langs.svg

      # 5. Сохраняем файлы прямо в ветку output без затирания старых данных
      - name: Push SVGs to output branch
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'output'
          commit-message: 'Update GitHub Statistics'
          force-add: 'true'
          files: dist/
